config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: 'characters#choose' #afficher la page avec les deux liens rick & morty


  resources :characters, only: [:index, :show ] do
    resources :bookings, only: [ :new, :create]
    resources :rating, only: [:show, :new, :create, :update]
  end

  resources :bookings, only: [ :show, :update]


  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, class_name: "User"
end

app/models/character.rb
class Character < ApplicationRecord
  # has_many :bookings
  # belongs_to :booking
  CATEGORIES = ["Rick", "Morty"]
  validates :category, inclusion: { in: CATEGORIES}
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    character_id = params[:character_id]
    associated_character_id = params[:associated_character_id]
    customer_id = params[:customer_id]
    if user_signed_in? == false
      redirect_to new_user_session_path, alert: "Buuuuuurp … Wubba Lubba dub-dub you need to sign yourself in ! 🤦‍♂️"
    else
      @booking = Booking.new(main_character_id: character_id, associated_character_id: associated_character_id)
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.save
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:main_character_id, :associated_character_id).permit(:rick_rating_id, :morty_rating_id)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    def choose
    end

    def index
      @category = params[:character]
      if @category.present? 
        @characters = Character.where(category: @category)
      else
        @characters = Character.all #le rick et morty de la mort TO DO !!!
      end
    end

    def show
      if params[:source] ==  
        @character = Character.find(params[:id])
      end

      @category = ""
      if @character.category == "Rick"
        @category = "Morty"
      else
        @category = "Rick"
      end
      
      if params[:source] != "character_show"
        @associated_characters = Character.where(category: @category)
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Your current booking 🪐 </h1>

    <div class= "container">
        <div class="row">
            <div class="col ">
                <div class="card">
                    <% character = Character.find(params["character_id"]) %>
                            <div class="card-img-top">
                              <% if Character.find(params["character_id"]).category == 'Rick' %>
                                <% if File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.jpg" %>
                                  <%= image_tag ("#{character.photo_url}.jpg"), id: 'img' %>
                                <% elsif File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.png" %>
                                   <%= image_tag ("#{character.photo_url}.png"), id: 'img' %>
                                <% end %>
                              <% elsif Character.find(params["character_id"]).category == 'Morty' %>
                                <% if File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.jpg" %>
                                  <%= image_tag ("#{character.photo_url}.jpg"), id: 'img' %>
                                <% elsif File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.png" %>
                                   <%= image_tag ("#{character.photo_url}.png"), id: 'img' %>
                                <% end %>
                              <% end %>
                            </div>

                        <h5><%= character.name %> </h5>
                        <h6><%= character.description %> </h6>
                            <div class="btn btn-primary">
                                <%= link_to "Description", character_path(character, source:"character_show")%>
                            </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <% associated_character = Character.find(params["associated_character_id"]) %>
                            <div class="card-img-top">
                                <div>
                                  <% if Character.find(params["associated_character_id"]).category == 'Rick' %>
                                    <% if File.file? "#{Rails.root}/app/assets/images/#{associated_character.photo_url}.jpg" %>
                                      <%= image_tag ("#{associated_character.photo_url}.jpg"), id: 'img' %>
                                    <% elsif File.file? "#{Rails.root}/app/assets/images/#{associated_character.photo_url}.png" %>
                                       <%= image_tag ("#{associated_character.photo_url}.png"), id: 'img' %>
                                    <% end %>
                                  <% elsif Character.find(params["associated_character_id"]).category == 'Morty' %>
                                    <% if File.file? "#{Rails.root}/app/assets/images/#{associated_character.photo_url}.jpg" %>
                                      <%= image_tag ("#{associated_character.photo_url}.jpg"), id: 'img' %>
                                    <% elsif File.file? "#{Rails.root}/app/assets/images/#{associated_character.photo_url}.png" %>
                                       <%= image_tag ("#{associated_character.photo_url}.png"), id: 'img' %>
                                    <% end %>
                                  <% end %>
                                </div>
                            <h5><%= associated_character.name %> </h5>
                            <h6><%= associated_character.description %> </h6>
                            <div class="btn btn-primary">
                                <%= link_to "Description", character_path(associated_character,  source:"character_show")%>
                            </div>

                </div>
            </div>
        </div>
    </div>

app/views/characters/_character_detail.html.erb
<!-- <h1>characters#show</h1>
 -->

 <div class="container">
   <h2><%= character.name %>_</h2>
 </div>

<div class="container row py-5">
  <div class="col-4 ">
    <% if File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.jpg" %>
      <%= image_tag ("#{character.photo_url}.jpg"), id: 'img' %>
    <% elsif File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.png" %>
       <%= image_tag ("#{character.photo_url}.png"), id: 'img' %>
    <% end %>
  </div>

  <div class="col-4">
    <%= character.description %>
  </div>
</div>

<br>

app/views/characters/choose.html.erb
<!-- Character#choose
 -->
 <div class="container py-5">
  <h1>Welcome to</h1>
    <%= image_tag ("logo_rickandmorty.svg")%>
 </div>

<div class="container py-5">
  <h2>Choose your first character_</h2>
</div>

<!-- barre PMU -->
<div class="wrapper">
  <p class="marquee"><span>And then we're gonna go on even more adventures after that, Morty and you're gonna keep your mouth shut about it, Morty, because the world is full of idiots that don't understand what's important, and they'll tear us apart, Morty but if you stick with me, I'm gonna accomplish great things, Morty, and you're gonna be part of them, and together, we're gonna run around, Morty. We're gonna do all kinds of wonderful things, Morty. Just you and me, Morty. The outside world is our enemy, Morty. We're the only friends we've got, Morty. It's just Rick and Morty. Rick and Morty and their adventures, Morty. Rick and Morty forever and forever. Morty's things. Me and Rick and Morty running around, and Rick and Morty time. All day long, forever. All a hundred days. Rick and Morty forever 100 times. Over and over, rickandmortyadventures.com. All 100 years. Every minute, rickandmorty.com.</span></p>
</div>


<div class="container">
  <div class="row">

    <div class="col justify-content-between">
      <div>
        <%= image_tag ("rick.svg")%>
      </div>
      <br>
      <div class="btn btn-primary btn-lg">
       <%= link_to "Rick", characters_path(character: "Rick") %>
      </div>
    </div>


    <div class="col">
      <div>
        <%= image_tag ("morty.svg")%>
      </div>
      <br>
      <div class="btn btn-primary btn-lg">
         <%= link_to "Morty", characters_path(character: "Morty") %>
      </div>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<!-- <h1>characters#index</h1> -->
<div class="container">
  <h2>Start by choosing your favorite <%= @category %>_</h2>
</div>
<div class=" cards col-9 ">
  <% @characters.each do |character| %>
    <div class="col">
      <div class="card col " style="width: 18rem;">
        <% if File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.jpg" %>
          <%= image_tag ("#{character.photo_url}.jpg"), id: 'img' %>
        <% elsif File.file? "#{Rails.root}/app/assets/images/#{character.photo_url}.png" %>
           <%= image_tag ("#{character.photo_url}.png"), id: 'img' %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"> <%= character.name %> </h5>
         <%= link_to "More details", character_path(character), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>



<!-- fixed ascii image
 -->
<% if @category == "Rick" %>
  <div class="fixed-img">
    <%= image_tag ("rick.svg")%>
  </div>
<% else %>
  <div class="fixed-img">
    <%= image_tag ("morty.svg")%>
  </div>
<% end %>




<!-- <div class="toggle">
  <input type="checkbox" name="switch" id="switch">
  <label class="label" for="switch"> <%= @category %> </label>
</div> -->

<!-- link_to characters path la même page mais avec l'autre catégorie parametres categorie=
 -->
<!-- <img src="..." class="card-img-top" alt="..." >
 -->

app/views/characters/show.html.erb
<div class="container">
  <%= render 'character_detail', character: @character %>
</div>
  <% unless @associated_characters.nil? %>
      <div class="container">
        <h2>Choose the associated <%= @category %>_ </h2>
      </div>
<div class="container cards">
    <% @associated_characters.each do |associated_character| %>
      <div class="col">
        <div class="card py-5" style="width: 18rem;">
          <% if File.file? "#{Rails.root}/app/assets/images/#{associated_character.photo_url}.jpg" %>
            <%= image_tag ("#{associated_character.photo_url}.jpg"), id: 'img' %>
          <% elsif File.file? "#{Rails.root}/app/assets/images/#{associated_character.photo_url}.png" %>
            <%= image_tag ("#{associated_character.photo_url}.png"), id: 'img' %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"> <%= associated_character.name %> </h5>
            <%= link_to "Pair with this character", new_character_booking_path(@character.id , associated_character_id: associated_character.id), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RickAndMortyRentalServices</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <%= link_to (image_tag ("Logo.png")), root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <% if user_signed_in? == false %>
          <div class="btn btn-primary align-items-center">
          <%= link_to "Sign In", new_user_session_path %>
          </div>
        <% else %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" id="font-color" href="#"><%= current_user.email %></a>
              </li>
              <li class="nav-item dropdown">
                <%= image_tag ("Morty_on.png"), class:"avatar dropdown-toggle", id:"navbarDropdown", data:{toggle: "dropdown"}, aria:{haspopup: true, expanded: false} %>
                <div class="dropdown-menu dropdown-menu-right" id="black-background" aria-labelledby="navbarDropdown">
                  <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item", id:"font-color" %>
                </div>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>